// lightmap-manager.js — Load, blend, and apply baked lightmaps to terrain material
// Lightmaps are generated by: node scripts/bake-lightmaps.mjs
import * as THREE from 'three';

const HOURS = [6, 9, 12, 15, 18, 21];

// ── Blend two greyscale ImageData arrays into a DataTexture ──────────────────
function _blendToTexture(imgA, imgB, t, size) {
  const data = new Uint8Array(size * size * 4);
  for (let i = 0; i < size * size; i++) {
    const a = imgA ? imgA[i] : 255;
    const b = imgB ? imgB[i] : 255;
    const v = Math.round(a + (b - a) * t);
    data[i * 4    ] = v;
    data[i * 4 + 1] = v;
    data[i * 4 + 2] = v;
    data[i * 4 + 3] = 255;
  }
  return data;
}

// ── Load a PNG as raw pixel array ────────────────────────────────────────────
async function _loadGrey(url, size) {
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = canvas.height = size;
      const ctx = canvas.getContext('2d');
      ctx.drawImage(img, 0, 0);
      const raw = ctx.getImageData(0, 0, size, size).data;
      // Keep only R channel (greyscale)
      const grey = new Uint8Array(size * size);
      for (let i = 0; i < size * size; i++) grey[i] = raw[i * 4];
      resolve(grey);
    };
    img.onerror = () => resolve(null);
    img.src = url;
  });
}

export class LightmapManager {
  /**
   * @param {THREE.Material} terrainMaterial   — TERRAIN_MAT from chunk.js
   * @param {number} lmSize                     — texture size (1024)
   * @param {number} aoIntensity                — aoMapIntensity on material
   */
  constructor(terrainMaterial, lmSize = 1024, aoIntensity = 1.2) {
    this._mat        = terrainMaterial;
    this._size       = lmSize;
    this._aoInt      = aoIntensity;
    this._loaded     = false;
    this._lmPixels   = {};   // hour → Uint8Array (R channel)
    this._tex        = null; // THREE.DataTexture, reused each blend
    this._lastHour   = -1;
    this._lastBlend  = -1;
  }

  /** Call once after game starts. Loads all lightmaps async. */
  async init() {
    try {
      // Try to load manifest to confirm lightmaps exist
      const r = await fetch('/lightmaps/manifest.json');
      if (!r.ok) { console.warn('[LM] No lightmaps found — run: node scripts/bake-lightmaps.mjs'); return; }
      const mf = await r.json();
      const size = mf.size || this._size;
      this._size = size;

      // Load all hour lightmaps in parallel
      const promises = HOURS.map(async h => {
        const key = String(h).padStart(2, '0');
        const px = await _loadGrey(`/lightmaps/lm_${key}h.png`, size);
        if (px) this._lmPixels[h] = px;
      });
      await Promise.all(promises);

      const loaded = Object.keys(this._lmPixels).length;
      if (loaded === 0) { console.warn('[LM] Lightmap PNGs not found in /lightmaps/'); return; }

      // Create DataTexture once (reused every frame)
      this._tex = new THREE.DataTexture(
        new Uint8Array(size * size * 4),
        size, size,
        THREE.RGBAFormat,
        THREE.UnsignedByteType
      );
      this._tex.wrapS = this._tex.wrapT = THREE.ClampToEdgeWrapping;
      this._tex.flipY = true;  // PNG origin is top-left; UV origin is bottom-left
      this._tex.needsUpdate = true;

      // Apply to material
      this._mat.aoMap = this._tex;
      this._mat.aoMapIntensity = this._aoInt;
      this._mat.needsUpdate = true;

      this._loaded = true;
      console.log(`[LM] ✓ Loaded ${loaded} lightmaps (${size}px)`);

      // Apply initial time
      this.update(12, 0);
    } catch (e) {
      console.warn('[LM] Error loading lightmaps:', e);
    }
  }

  /**
   * Call every game frame (or at least when time changes).
   * @param {number} gameHour  — current game hour (0–24, float ok)
   * @param {number} _dt       — unused, kept for signature compat
   */
  update(gameHour, _dt) {
    if (!this._loaded) return;

    // Find the two surrounding hour slots
    let iA = HOURS.length - 1;
    for (let i = 0; i < HOURS.length; i++) {
      if (HOURS[i] <= gameHour) iA = i;
    }
    const iB    = (iA + 1) % HOURS.length;
    const hA    = HOURS[iA];
    const hB    = HOURS[iB] < hA ? HOURS[iB] + 24 : HOURS[iB]; // wrap midnight
    const blend = Math.max(0, Math.min(1, (gameHour - hA) / (hB - hA)));

    // Skip if nothing changed (avoid texture upload every frame)
    const blendKey = hA * 1000 + Math.round(blend * 100);
    if (blendKey === this._lastBlend) return;
    this._lastBlend = blendKey;

    const pixA = this._lmPixels[HOURS[iA]] || null;
    const pixB = this._lmPixels[HOURS[iB]] || null;

    const newData = _blendToTexture(pixA, pixB, blend, this._size);
    this._tex.image.data.set(newData);
    this._tex.needsUpdate = true;
  }

  get isLoaded() { return this._loaded; }
}
